### ISSUE TITLE
No config file

### ISSUE THREAD

**Issue by waynemichel** [ca-team-sulley/bolt-extension-html5-audio#2]
I have installed both versions of the extension and neither install the config file into app/config/extensions.

I have install other extensions and they install correctly with the config file.

**Comment by waynemichel** [comment]
I also get this error message:
In the contenttype for 'Page', the field 'audio' has 'type: audio', which is not a proper field type. Please edit contenttypes.yml, and correct this.

**Comment by jkazimir** [comment]
Hi,

I haven't seen this happen yet, but I'm interested to reproduce it.  With both the config file not installed, as well as the field type not being present, it sounds like the installation isn't completing.  Did you notice any errors during the installation?  Also, what version of Bolt are you trying to install on?

**Comment by waynemichel** [comment]
Using Bolt 2.2.20

All appeared to install normally:

```
  Installing package
```

Loading composer repositories with package information
Updating dependencies
- Installing cainc/html5-audio (v1.0.0)
   Loading from cache

> Bolt\Composer\ExtensionInstaller::handle
> Writing lock file
> Generating autoload files

```
  Installation complete
```

You can now start using the installed extension, documentation and 
implementation instructions can be found using the link below.

regards

On 01/05/16 01:46, Jared Kazimir wrote:

> Hi,
> 
> I haven't seen this happen yet, but I'm interested to reproduce it. 
> With both the config file not installed, as well as the field type not 
> being present, it sounds like the installation isn't completing. Did 
> you notice any errors during the installation? Also, what version of 
> Bolt are you trying to install on?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/ca-team-sulley/bolt-extension-html5-audio/issues/2#issuecomment-215974415

## 

Waynes Web Shop dot com

for Support / Site updates, use a support ticket for the fastest service

Click to open a support ticket http://wayneswebshop.com/support

Phone: 0490 066 472

**Comment by jkazimir** [comment]
Ok, found it! Sorry about this… It came down to initialization not happening properly when loaded from the store. Wish I had noticed this sooner, but also had a local version of the extension installed, which prevented me from seeing this.

Updating to v1.0.2 should get things working for you.

Thanks!
