### ISSUE TITLE
Bolt v3 version?

### ISSUE THREAD

**Issue by SvanteRichter** [ca-team-sulley/bolt-extension-html5-audio#3]
Hey,

Do you guys have any plans to port this to bolt v3?

Thanks for the extension!

**Comment by jkazimir** [comment]
Hey SahAssar!

Time's a bit tight at the moment, but I should have some time in the next few weekends to get this ported.

**Comment by jkazimir** [comment]
Welp, I've certainly lost track of this one...

With many thanks to @psanchezg, 2.0 has been tagged, bringing support to Bolt 3!
